# Configuration Overrides

#environment = "development"        # Environment: development, production
debug_mode = true                   # Enable or disable debug mode
log_level = "Trace"                 # Logging level: Info, Debug, Error, etc.


[aggregator]
socket_path = "/tmp/manager.sock"    # Path to the socket
socket_permission = 0o777
